spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle9Dialect
      javax:
        persistence:
          query:
            timeout: 600000
    open-in-view: true

  #  liquibase:
  #    change-log:
  #      classpath: /db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:oracle:thin:@192.168.31.13:1521:GDBCSCP1
    username: DEPO
    password: DEPO
    driver-class-name: oracle.jdbc.OracleDriver
    dbcp2:
      test-while-idle: true
    tomcat:
      validation-query: SELECT 1
    hikari:
      auto-commit: true


server:
  port: 8080

